server:
  port: 8601
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: ptu123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8500/eureka/
  instance:
    hostname: localhost
mybatis:
  mapper-locations: classpath:/mapper/*