server:
  port: 8893
spring:
  application:
    name: user-consumer
  thymeleaf:
    cache: false
    prefix: classpath:/template/
    suffix: .html
    encoding: UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8500/eureka/
  instance:
    hostname: localhost
feign:
  circuitbreaker:
    enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000